sudo: required
language: go

services:
  - docker

go:
  - 1.10.x

install:
  - make deps

before_script:
  - make test

script:
  - make build

after_success:
  - make docs

notifications:
  slack: $ST_TOKEN

deploy:
  - provider: pages
    local_dir: docs/output
    skip_cleanup: true
    github_token: $GH_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
