sudo: required
language: go

services:
  - docker

go:
  - 1.10.x

install:
  - make deps

before_script:
  - make test

script:
  - make build

after_success:
  - make docs

notifications:
  slack: $ST_TOKEN